debug: True

mail_host: host:port
mail_port: 25 
mail_user: username
mail_pass: password
mail_from: local@localhost
admins:
 - mail@xeroc.org

project_name: MINT
project_sub_name: BOS Manual Intervention Module
secret_key: RUR7LywKvncb4eoR

sql_database: "sqlite:///{cwd}/bookied-local.db"

connection:
    use: TestCharlie
    Main:
        node:
            - 

    Test:
        node:
            - wss://peerplays-dev.blocktrades.info/ws
        nobroadcast: True
        num_retries: 1
        
    TestOSE:
        node:
            - wss://peerplays-dev.blocktrades.info/alpha/ws
        nobroadcast: False
        num_retries: 1
        
    TestCharlie:
        node:
            - ws://ec2-35-183-1-21.ca-central-1.compute.amazonaws.com:8090
        nobroadcast: False
        num_retries: 1

allowed_transitions:
    EventStatus:
        upcoming:
            - in_progress
            - finished
            - frozen
            - canceled
        in_progress:
            - finished
            - frozen
            - canceled
        finished:
            - settled
            - canceled
        frozen:
            - upcoming
            - in_progress
            - frozen
            - canceled
    BettingMarketGroupStatus:
        upcoming:
            - closed
            - canceled
            - in_play
            - frozen
        in_play:
            - frozen
            - closed
            - canceled
        closed:
            - graded
            - canceled
        graded:
            - re_grading
            - settled
            - canceled
        re_grading:
            - graded
            - canceled
    BettingMarketStatus:
        unresolved:
            - win
            - not_win
            - canceled
            - frozen
        frozen:
            - unresolved
            - win
            - not_win
            - canceled
        win:
            - not_win
            - canceled
        not_win:
            - canceled
            - win
