debug: False

project_name: MINT
project_sub_name: The BOS Manual Intervention Module
secret_key: # enter any random string 

sql_database: "sqlite:///{cwd}/bookied-local.db"

connection:
    use: # enter your desired chain

    baxter:
        node:
            - # enter your node
        nobroadcast: False
        num_retries: 1

allowed_assets:
    - BTF
    - BTC
    - PPY
    - BTCTEST

allowed_transitions:
    EventStatus:
        create:
            - upcoming
        upcoming:
            - in_progress
            - finished
            - frozen
            - canceled
        in_progress:
            - finished
            - frozen
            - canceled
        finished:
            - settled
            - canceled
        frozen:
            - upcoming
            - in_progress
            - frozen
            - canceled
    BettingMarketGroupStatus:
        create:
            - upcoming
        upcoming:
            - closed
            - canceled
            - in_play
            - frozen
        in_play:
            - frozen
            - closed
            - canceled
        closed:
            - graded
            - canceled
        graded:
            - re_grading
            - settled
            - canceled
        re_grading:
            - graded
            - canceled
    BettingMarketStatus:
        create:
            - unresolved
        unresolved:
            - win
            - not_win
            - canceled
            - frozen
        frozen:
            - unresolved
            - win
            - not_win
            - canceled
        win:
            - not_win
            - canceled
        not_win:
            - canceled
            - win
